### PR TITLE
Only capture locals that are directly referred to by the function

### LINKED ISSUE #10: Naive handling of infinite seq's in the &env
``` clj
(let [[a b] (iterate inc 1)] (serializable.fn/fn []))
```

Will try to consume the entire infinite seq even though nothing refers to it.  This is because destructuring let will expand into a form that assigns the `(iterate inc 1)` sequence to a gensym.  So it becomes part of &env and then serializable.fn tries to serialize it.

Obviously there is no way to completely avoid this, since infinite seq's are valid values.  However in the example case, nothing even refers to it in the function itself.  

I have a small assertion lib that also captures the env, and it handles this case correctly.  It filters out any env entries that are not referred to in the asserted expression.

serializable.fn could do the same thing.

https://github.com/RedHatQE/test.assert/blob/master/src/test/assert.clj#L357-369

### PR DESCRIPTION
**Pull request by weissjeffm**
Fixes #10

### CODE REVIEW

**Comment by technomancy** [comment]
Would this break for functions which invoke macros involving intentional symbol capture?

**Comment by weissjeffm** [comment]
All this does is say 'if this local isn't referred to in the function itself, don't serialize it as part of the surrounding `let`'.  

I can't think of any reason why it would matter what the function expands to internally.  The behavior should be the same as if it were written expanded to begin with.  Is that bad?  If it captures a local, then yes, the local would be printed as part of the serialization.  If that local happens to be an infinite seq, then that would be bad, but no worse than before this patch.

All that said, I haven't tried it so I may be missing something.

**Comment by weissjeffm** [comment]
Oh I think I see what you're saying, the data i'm parsing for symbols is the un-expanded function.  So if it expands to capture a local, then that local would not be printed.

**Comment by technomancy** [comment]
Yeah, typically it's considered bad form to write macros that do this, but there might me weird edge cases where it makes sense, and I'm not sure it's a good idea for this functionality to interfere with it.

**Pull request closed without merging**
